version: "3.9"

services:
  database:
    container_name: db
    image: postgres
    hostname: database
    restart: always
    environment:
#      POSTGRES_PASSWORD: postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"


  client:
    container_name: eureka-client
    build:
     context: ./eureka-client
     dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone = http://eureka:8080/eureka/
      - DB_URL=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - server
#    hostname: client
    ports:
      - "8081:8081"
    links:
      - server
      - database

  gateway:
    container_name: api-gateway
    depends_on:
      - server
    build: ./api-gateway
    hostname: gateway
    expose:
      - 8082
    ports:
      - "8082:8082"
    environment:
#     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8080/eureka
      - eureka.client.service-url.defaultZone = http://eureka:8080/eureka/

